# Generated by Django 3.2.5 on 2021-07-21 12:28

from django.conf import settings
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=upload.models.upload_path)),
                ('caption', models.TextField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=11)),
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False)),
                ('contributor', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.DeleteModel(
            name='HashTags',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.ManyToManyField(default=None, through='upload.Post', to='upload.Images'),
        ),
        migrations.AddField(
            model_name='images',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='upload.theme'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upload.tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
