# Generated by Django 3.2.5 on 2021-07-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210721_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ManyToManyField(to='upload.Tags'),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
